apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  type: NodePort
  selector:
    app: scaletestapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080